### PR TITLE
Use HTTPS when fetching JSON files

### PR DESCRIPTION
**Pull request by jvehent**

### CODE REVIEW

**Comment by pmclanahan** [comment]
Can't believe I never noticed and fixed this. Thank you!

**Comment by jgmize** [comment]
@jvehent as you know, the data this is library fetches is public, so the only benefit of using https would be preventing a MITM attack against the client. However, as we discussed in IRC just changing the default url to https doesn't actually help unless the requests validate the cert, which does not appear to be the case: we are [currently using urllib2](https://github.com/mozilla/django-product-details/blob/master/product_details/management/commands/update_product_details.py#L135-L136) which [until recently](http://legacy.python.org/dev/peps/pep-0476/) did not verify certs by default.

**Comment by pmclanahan** [comment]
Still better than not using https right? A bit less obvious?

**Comment by jgmize** [comment]
@pmclanahan you merged this just as I was finishing that comment above. We should follow up with a PR to either ensure urllib2 verify certs or a switch to using the requests library.

**Comment by jgmize** [comment]
To be clear, there's no downside to switching the default url to https, and newer versions of python (and therefore urllib2) will verify certs by default.

**Comment by jgmize** [comment]
Researching a little further, "newer versions of python" incudes python [2.7.9](https://www.python.org/downloads/release/python-279/) and above, and [3.4](https://docs.python.org/3.4/whatsnew/3.4.html) and above, may be a fairly reasonable expectation at this point-- we might just add a note to the [change log](https://github.com/mozilla/django-product-details#change-log) for 0.8.2 encouraging folks to verify that they aren't running a version of python with this issue.

**Pull request merged**
