### PR TITLE
Fix #76: Update for 3-digit version numbers

### LINKED ISSUE #76: Update django-product-details for FF 100+
We're approaching FF release number 100 in 2022, so let's get ahead of that in terms of this library

## Success criteria
- [ ] Tests updated to prove three-digit version numbers will not be a problem
- [ ] CI tests are run on Circle CI or GH actions

### PR DESCRIPTION
**Pull request by robhudson**

### CODE REVIEW

**Comment by stevejalim** [comment]
@robhudson Let's also edit `__init__.py` bump this version to 15.0.1 - what do you think?

**Comment by robhudson** [comment]
> @robhudson Let's also edit `__init__.py` bump this version to 15.0.1 - what do you think?

I was thinking the version bumps are separate commits related to releases. I can add a separate commit to this PR though if that's the plan.

**Comment by stevejalim** [comment]
@robhudson I'm cool with having the verison bump as an additional commit, yeah - am happy as long as the improved behaviour is reflected in a specific version

**Comment by robhudson** [comment]
@stevejalim Just FYI: The latest product details is 1.0.0 now... https://github.com/mozilla/django-product-details/blob/master/product_details/__init__.py#L13

**Comment by stevejalim** [comment]
@robhudson Good point - I was looking at the GH tags. So `1.0.1` work for you?

**Review by stevejalim — APPROVED** [review]
LGTM - thanks for this!

**Pull request merged**
