### PR TITLE
Convert README.md to rST.

### PR DESCRIPTION
**Pull request by pmclanahan**
This was done automatically using pandoc, and was
mainly done because currently reStructured Text
is the only format supported by PyPI.

### CODE REVIEW

**Comment by pmclanahan** [comment]
@jezdez @fwenzel r? This is much more straight forward and easily managed than the previous PR.

**Comment by jezdez** [comment]
The manifest template also lists the Markdown version and needs to be fixed

**Comment by pmclanahan** [comment]
Bah! Great catch jezdez. Fixed.

**Comment by pmclanahan** [comment]
Unless there are objections, I'll merge this soon.

**Comment by pmclanahan** [comment]
I'm going to wait on this until after #39 merges and do one last conversion to catch the changes.

**Pull request closed without merging**
